<?php
declare(strict_types=1);

$mockNews = [
    [
        'id' => 1,
        'image' => 'news_69bfb8a8c3a62.jpeg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'Новые цифровые сервисы запущены в Казахстане',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Политика',
        'cat_name' => 'Политика',
        'category_slug' => 'politics',
        'author_name' => 'Алихан Сейсенов',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 2,
        'image' => 'news_69c42acf42755.jpg',
        'inner_image' => null,
        'views' => 89,
        'created_at' => '2026-05-08 18:30:00',
        'title' => 'Крупное спортивное событие собрало тысячи зрителей',
        'content' => 'Демонстрационный текст спортивной новости.',
        'category_name' => 'Спорт',
        'cat_name' => 'Спорт',
        'category_slug' => 'sport',
        'author_name' => 'Чарли Чапман',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 3,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 56,
        'created_at' => '2026-05-07 09:15:00',
        'title' => 'Мировые новости: главные события недели',
        'content' => 'Тестовый текст для раздела мировых новостей.',
        'category_name' => 'Мир',
        'cat_name' => 'Мир',
        'category_slug' => 'world',
        'author_name' => 'Боб Стоун',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 4,
        'image' => 'news_69bfb8a8c3a62.jpeg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'Новые цифровые сервисы запущены в Казахстане',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Шоу-Бизнес',
        'cat_name' => 'Шоу-Бизнес',
        'category_slug' => 'showbiz',
        'author_name' => 'Adilet Zhaksylyk',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 5,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 6,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 7,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
    ],
    [
        'id' => 8,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
    ],
];