<?php
declare(strict_types=1);

$mockNews = [
    [
        'id' => 1,
        'image' => 'einstein.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'Новые цифровые сервисы запущены в Казахстане',
        'content' => 'Краткое описание новости для главной страницы. 
        
        Казахстан запускает первую полностью цифровую систему студенческих общежитий
В Казахстан стартовал пилотный проект по внедрению полностью цифровой системы управления студенческими общежитиями. Новая платформа позволит студентам подавать заявки онлайн, отслеживать очередь на заселение и получать уведомления через мобильное приложение.
По данным представителей Министерства науки и высшего образования, система уже тестируется в нескольких университетах Астана и Алматы. Разработчики отмечают, что цифровизация поможет сократить бюрократию и уменьшить количество спорных ситуаций при распределении мест.
«Наша цель — сделать процесс максимально прозрачным и удобным для студентов», — сообщил представитель проекта на презентации в столице.
Также в систему планируют добавить функции электронного пропуска, оплаты проживания и подачи заявок на ремонт комнат. Полноценный запуск платформы по всей стране ожидается к началу следующего учебного года.',
        'category_name' => 'Политика',
        'cat_name' => 'Политика',
        'category_slug' => 'politics',
        'author_name' => 'Алихан Сейсенов',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 2,
        'image' => 'news_69c42acf42755.jpg',
        'inner_image' => null,
        'views' => 89,
        'created_at' => '2026-05-08 18:30:00',
        'title' => 'Крупное спортивное событие собрало тысячи зрителей',
        'content' => 'Демонстрационный текст спортивной новости.',
        'category_name' => 'Спорт',
        'cat_name' => 'Спорт',
        'category_slug' => 'sport',
        'author_name' => 'Чарли Чапман',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 3,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 56,
        'created_at' => '2026-05-07 09:15:00',
        'title' => 'Мировые новости: главные события недели',
        'content' => 'Тестовый текст для раздела мировых новостей.',
        'category_name' => 'Мир',
        'cat_name' => 'Мир',
        'category_slug' => 'world',
        'author_name' => 'Боб Стоун',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 4,
        'image' => 'news_69bfb8a8c3a62.jpeg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'Новые цифровые сервисы запущены в Казахстане',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Шоу-Бизнес',
        'cat_name' => 'Шоу-Бизнес',
        'category_slug' => 'showbiz',
        'author_name' => 'Adilet Zhaksylyk',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 5,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 6,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 7,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 8,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 124,
        'created_at' => '2026-05-09 12:00:00',
        'title' => 'New hello in analytics worlds',
        'content' => 'Краткое описание новости для главной страницы.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Nice Tits',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 9,
        'image' => 'news_69c42acf42755.jpg',
        'inner_image' => null,
        'views' => 210,
        'created_at' => '2026-05-06 14:20:00',
        'title' => 'Экономический форум: новые соглашения и перспективы',
        'content' => 'Подробности экономического форума в столице.',
        'category_name' => 'Аналитика',
        'cat_name' => 'Аналитика',
        'category_slug' => 'analytics',
        'author_name' => 'Мария Ким',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 10,
        'image' => 'news_69c68d390155e.jpg',
        'inner_image' => null,
        'views' => 342,
        'created_at' => '2026-05-05 11:00:00',
        'title' => 'Технологический прорыв в области ИИ',
        'content' => 'Как искусственный интеллект меняет нашу жизнь.',
        'category_name' => 'Мир',
        'cat_name' => 'Мир',
        'category_slug' => 'world',
        'author_name' => 'Рустем Ахметов',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 11,
        'image' => 'news_69bfb8a8c3a62.jpeg',
        'inner_image' => null,
        'views' => 156,
        'created_at' => '2026-05-04 16:45:00',
        'title' => 'Культурное наследие: выставка редких артефактов',
        'content' => 'Уникальная возможность увидеть историю своими глазами.',
        'category_name' => 'Шоу-Бизнес',
        'cat_name' => 'Шоу-Бизнес',
        'category_slug' => 'showbiz',
        'author_name' => 'Дана Омарова',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
    [
        'id' => 12,
        'image' => 'einstein.jpg',
        'inner_image' => null,
        'views' => 88,
        'created_at' => '2026-05-03 10:30:00',
        'title' => 'Экологические инициативы в крупных городах',
        'content' => 'Как мегаполисы борются за чистоту воздуха.',
        'category_name' => 'Политика',
        'cat_name' => 'Политика',
        'category_slug' => 'politics',
        'author_name' => 'Ерасыл Нурлан',
        'status' => 'approved',
        'language' => 'ru',
        'comments' => 5,
    ],
];